name: publish-release
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  generate-map:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install remotemaker
        run: |
          python -m pip install ${{ vars.REMOTE_MAKER_WHEEL }}
      - name: run remotemaker
        run: |
          python -m remotemaker \
                 --server ${{ vars.STAGING_MAP_SERVER }} \
                 --token ${{ secrets.STAGING_SERVER_TOKEN }} \
                 --source ${{ github.server_url }}/${{ github.repository }} \
                 --manifest manifest.json \
                 --commit release
